//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPDP_Charts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TPDP_Charts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;wikitable floatleft&quot; border=&quot;1&quot; cellspacing=&quot;0px&quot; cellpadding=&quot;2px&quot;&gt;
        ///
        ///&lt;tbody&gt;&lt;tr align=&quot;center&quot;&gt;
        ///&lt;td&gt;A/D
        ///&lt;/td&gt;
        ///&lt;th width=&quot;26px&quot; style=&quot;background: #FFBBE6; color: #000000;&quot;&gt;Voi
        ///&lt;/th&gt;
        ///&lt;th width=&quot;26px&quot; style=&quot;background: #FF4949; color: #000000;&quot;&gt;Fir
        ///&lt;/th&gt;
        ///&lt;th width=&quot;26px&quot; style=&quot;background: #6884FF; color: #000000;&quot;&gt;Wtr
        ///&lt;/th&gt;
        ///&lt;th width=&quot;26px&quot; style=&quot;background: #57DC4D; color: #000000;&quot;&gt;Ntr
        ///&lt;/th&gt;
        ///&lt;th width=&quot;26px&quot; style=&quot;background: #C18458; color: #000000;&quot;&gt;Ear
        ///&lt;/th&gt;
        ///&lt;th width=&quot;2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///&lt;td&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Phlegmatic&quot; title=&quot;Phlegmatic&quot;&gt;Phlegmatic&lt;/a&gt;&lt;/b&gt;
        ///&lt;/td&gt;
        ///&lt;td&gt;The weather becomes Calm.
        ///&lt;/td&gt;
        ///&lt;td&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Sanguine&quot; title=&quot;Sanguine&quot;&gt;Sanguine&lt;/a&gt;&lt;/b&gt;
        ///&lt;/td&gt;
        ///&lt;td&gt;The weather becomes Aurora.
        ///&lt;/td&gt;
        ///&lt;td&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Melancholic&quot; title=&quot;Melancholic&quot;&gt;Melancholic&lt;/a&gt;&lt;/b&gt;
        ///&lt;/td&gt;
        ///&lt;td&gt;The weather becomes Heavy Fog.
        ///&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;&lt;b&gt;&lt;a href=&quot;/wiki/Choleric&quot; title=&quot;Choleric&quot;&gt;Choleric&lt;/a&gt;&lt;/b&gt;
        ///&lt;/td&gt;
        ///&lt;td&gt;The weather becomes Dust Storm.
        ///&lt;/td&gt;
        ///&lt;td&gt;&lt;b&gt;&lt;a href=&quot;/wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
    }
}
